# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: juhui
# "service" is the name of this project. This will also be added to your AWS resource names.
service: authService

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-southeast-2
  environment:
    CLIENT_ID: ${ssm:/CLIENT_ID} # securely fetch from the parameters store

functions:
  signUp:
    handler: handlers/signUp.signUp
    events:
      - httpApi:
          path: /signUp
          method: post
  confirmSignUp:
    handler: handlers/confirmSignUp.confirmSignUp
    events:
      - httpApi:
          path: /confirmSignUp
          method: post
  signIn:
    handler: handlers/signIn.signIn
    events:
      - httpApi:
          path: /signIn
          method: post
